services:
    Phoenix\EasyElasticsearchBundle\Search\:
        resource: '../../Search/*'
        arguments:
            - '@Phoenix\EasyElasticsearchBundle\Service\DocumentService'
            - '@Phoenix\EasyElasticsearchBundle\Utils\Pagination'
            - '@Phoenix\EasyElasticsearchBundle\Utils\Util'

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of ListenerInterface will be tagged automatically
        Phoenix\EasyElasticsearchBundle\Search\SearchInterface:
            tags: ['es.search']