services:
    Phoenix\ElasticsearchBundle\Document\:
        resource: '../../Document/*'

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of ListenerInterface will be tagged automatically
        Phoenix\ElasticsearchBundle\Document\DocumentInterface:
            tags: ['es.document']