services:
    Phoenix\EasyElasticsearchBundle\Service\:
        resource: '../../Service/*'

    Phoenix\EasyElasticsearchBundle\Service\ClientService:
        arguments: ['%es.hosts%']

    Phoenix\EasyElasticsearchBundle\Service\IndexService:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\ClientService']

    Phoenix\EasyElasticsearchBundle\Service\DocumentService:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\ClientService']

    Phoenix\EasyElasticsearchBundle\Utils\Util:
        class: Phoenix\EasyElasticsearchBundle\Utils\Util
        arguments: ['%kernel.project_dir%']

    Phoenix\EasyElasticsearchBundle\Utils\Pagination:
        class: Phoenix\EasyElasticsearchBundle\Utils\Pagination