services:
    Phoenix\ElasticsearchBundle\Service\:
        resource: '../../Service/*'

    Phoenix\ElasticsearchBundle\Service\ClientService:
        arguments: ['%pes.hosts%']

    Phoenix\ElasticsearchBundle\Service\IndexService:
        arguments: ['@Phoenix\ElasticsearchBundle\Service\ClientService']

    Phoenix\ElasticsearchBundle\Service\DocumentService:
        arguments: ['@Phoenix\ElasticsearchBundle\Service\ClientService']

    Phoenix\ElasticsearchBundle\Utils\Util:
        class: Phoenix\ElasticsearchBundle\Utils\Util
        arguments: ['%kernel.project_dir%']

    Phoenix\ElasticsearchBundle\Utils\Pagination:
        class: Phoenix\ElasticsearchBundle\Utils\Pagination