services:
    Phoenix\EasyElasticsearchBundle\Service\:
        resource: '../../Service/*'

    Phoenix\EasyElasticsearchBundle\Service\ClientService:
        arguments: ['%es.hosts%']

    Phoenix\EasyElasticsearchBundle\Service\IndexService:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\ClientService']