services:
    Phoenix\EasyElasticsearchBundle\Index\:
        resource: '../../Index/*'
        calls:
            - [setPrefix, ['%es.index_prefix%']]

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of IndexInterface will be tagged automatically
        Phoenix\EasyElasticsearchBundle\Index\IndexInterface:
            tags: ['es.index']