services:
    Phoenix\ElasticsearchBundle\Command\:
        resource: '../../Command/*'

    Phoenix\ElasticsearchBundle\Command\ClientCommand:
        arguments: ['@Phoenix\ElasticsearchBundle\Service\ClientService']

    Phoenix\ElasticsearchBundle\Command\IndexCommand:
        arguments: ['@Phoenix\ElasticsearchBundle\Service\IndexService', '@Phoenix\ElasticsearchBundle\Finder\IndexFinder']

    Phoenix\ElasticsearchBundle\Command\DocumentCommand:
        arguments:
            - '@Phoenix\ElasticsearchBundle\Utils\Util'
            - '@Phoenix\ElasticsearchBundle\Service\DocumentService'
            - '@Phoenix\ElasticsearchBundle\Finder\IndexFinder'

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of AbstractCommand will be tagged automatically
        Phoenix\ElasticsearchBundle\Command\AbstractCommand:
            tags: [console.command]