services:
    Phoenix\EasyElasticsearchBundle\Manager\IndexManager:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\IndexService', '%es.index_prefix%']

    Phoenix\EasyElasticsearchBundle\Manager\DocumentManager:
        class: Phoenix\EasyElasticsearchBundle\Manager\DocumentManager