services:
    Phoenix\ElasticsearchBundle\Finder\IndexFinder:
        arguments: [!tagged_iterator es.index]

    Phoenix\ElasticsearchBundle\Finder\SearchFinder:
        arguments: [!tagged_locator es.search]