services:
    Phoenix\EasyElasticsearchBundle\Command\:
        resource: '../../Command/*'

    Phoenix\EasyElasticsearchBundle\Command\ClientCommand:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\ClientService']

    Phoenix\EasyElasticsearchBundle\Command\IndexCommand:
        arguments: ['@Phoenix\EasyElasticsearchBundle\Service\IndexService', '@Phoenix\EasyElasticsearchBundle\Finder\IndexFinder']

    Phoenix\EasyElasticsearchBundle\Command\DocumentCommand:
        arguments:
            - '@Phoenix\EasyElasticsearchBundle\Utils\Util'
            - '@Phoenix\EasyElasticsearchBundle\Service\DocumentService'
            - '@Phoenix\EasyElasticsearchBundle\Finder\IndexFinder'

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of AbstractCommand will be tagged automatically
        Phoenix\EasyElasticsearchBundle\Command\AbstractCommand:
            tags: [console.command]