services:
    Phoenix\ElasticsearchBundle\Search\:
        resource: '../../Search/*'
        arguments:
            - '@Phoenix\ElasticsearchBundle\Service\DocumentService'
            - '@Phoenix\ElasticsearchBundle\Utils\Pagination'
            - '@Phoenix\ElasticsearchBundle\Utils\Util'

    # this config only applies to the services created by this file
    _instanceof:
        # services whose classes are instances of ListenerInterface will be tagged automatically
        Phoenix\ElasticsearchBundle\Search\SearchInterface:
            tags: ['es.search']